{
    "name": "Football Club Portal",
    "version": "19.0.1.0.0",
    "category": "Website",
    "license": "LGPL-3",
    "summary": "Football club website, events, and fan registration foundation.",
    "author": "Custom",
    "depends": [
        "base",
        "web",
        "portal",
        "website",
        "contacts",
        "mail",
        "account",
        "stock",
        "purchase",
        "hr",
    ],
    "data": [
        "security/football_club_security.xml",
        "security/ir.model.access.csv",
        "data/sequences.xml",
        "data/mail_templates.xml",
        "views/club_fan_views.xml",
        "views/club_event_views.xml",
        "views/football_club_menus.xml",
        "views/website_templates.xml",
        "views/website_menus.xml",
        "views/login_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "football_club_portal/static/src/css/football_club.css",
            "football_club_portal/static/src/css/club_home.css",
            "football_club_portal/static/src/css/club_events.css",
            "football_club_portal/static/src/css/club_login.css",
            "football_club_portal/static/src/js/fan_registration.js",
        ],
        "web.assets_frontend_minimal": [
            "football_club_portal/static/src/js/club_login.js",
        ],
    },
    "installable": True,
    "application": True,
}
