# Copyright 2022 Ecosoft Co., Ltd. (http://ecosoft.co.th)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "St George - Install",
    "summary": "Used to install other modules",
    "version": "19.0.1.0.0",
    "license": "AGPL-3",
    "category": "Customized",
    "author": "ATLAS Computer",
    "installable": True,
    "depends": [
        # Structure
        "account_asset_operating_unit",
        "account_asset_operating_unit_access_all",
        "account_asset_transfer_operating_unit",
        "account_financial_report_operating_unit",
        "account_operating_unit",
        "account_operating_unit_access_all",
        "account_payment_multi_deduction_operating_unit",
        "agreement_legal_operating_unit",
        "agreement_operating_unit",
        "agreement_operating_unit_access_all",
        "analytic_operating_unit",
        "analytic_operating_unit_access_all",
        "base_automation",
        "base_model_restrict_update",
        "base_tier_validation_correction",
        "base_tier_validation_report",
        "base_user_role",
        "base_user_role_restrict_update",
        "budget_allocation_operating_unit",
        "budget_allocation_operating_unit_access_all",
        "budget_control_operating_unit",
        "budget_control_operating_unit_access_all",
        "contract_operating_unit",
        "contract_operating_unit_access_all",
        "hr_expense_operating_unit",
        "hr_expense_operating_unit_access_all",
        "hr_operating_unit",
        "hr_operating_unit_access_all",
        "mis_builder_operating_unit",
        "mis_builder_operating_unit_access_all",
        "operating_unit",
        "operating_unit_access_all",
        "purchase_deposit_operating_unit",
        "purchase_operating_unit",
        "purchase_operating_unit_access_all",
        "purchase_request_operating_unit",
        "purchase_request_operating_unit_access_all",
        "purchase_request_to_requisition_operating_unit",
        "purchase_requisition_operating_unit",
        "purchase_requisition_operating_unit_access_all",
        "purchase_stock_operating_unit",
        # "purchase_work_acceptance_late_fines_operating_unit",
        "sale_operating_unit",
        "sale_operating_unit_access_all",
        "sale_stock_operating_unit",
        "sales_team_operating_unit",
        "stock_account_operating_unit",
        "stock_account_visible_valuation",
        "stock_operating_unit",
        "stock_operating_unit_access_all",
       
        "mis_builder",
        "purchase_stock_budget_allocation",
        "res_project",
        "res_project_sequence",
        "stock_budget_allocation",
        "stock_request_budget_allocation",
        # Procurement
        "purchase_deposit",
        "purchase_deposit_analytic",
        "purchase_invoice_plan",
        "purchase_invoice_plan_deposit",
        "purchase_invoice_plan_retention",
        "purchase_manual_currency",
        "purchase_request",
        "purchase_request_cancel_confirm",
        "purchase_request_manual_currency",
        "purchase_request_tier_validation",
        "purchase_request_to_requisition_manual_currency",
        "purchase_requisition_manual_currency",
        "purchase_rfq_number",
        "purchase_stock_analytic",
        "purchase_tax_adjust",
        "purchase_tier_validation",
        "purchase_work_acceptance",
        "purchase_work_acceptance_evaluation",
        "purchase_work_acceptance_invoice_plan",
        "purchase_work_acceptance_late_fines",
        "purchase_work_acceptance_tier_validation",
        # "purchase_work_acceptance_late_fines_budget",
        # "purchase_work_acceptance_late_fines_fund",
        # Accounting
        "account_check_date",
        "account_check_payee",
        "account_check_printing_report_base",
        "account_financial_report",
        "account_financial_report_extension",
        "account_fiscal_year",
        "account_invoice_origin_link",
        "account_invoice_sale_origin_link",
        "account_journal_lock_date",
        "account_lock_date_update",
        "account_manual_currency",
        "account_move_line_stock_info",
        "account_move_reconcile_no_cancel",
        "account_move_unreconcile_payment_cancel",
        "account_payment_disable_draft",
        "account_payment_multi_deduction",
        "account_reconciliation_widget",
        "account_reconciliation_widget_extension",
        "account_sequence_option",
        # "account_spread_cost_revenue",
        # "account_spread_cost_revenue_enhanced",
        "account_statement_import_txt_xlsx",
        "account_usability",
        "hr_expense_advance_clearing",
        "hr_expense_advance_clearing_sequence",
        "hr_expense_advance_overdue_reminder",
        "hr_expense_cancel_confirm",
        "hr_expense_cancel_policy",
        "hr_expense_disable_confirm_duplicate",
        "hr_expense_excluded_tax",
        "hr_expense_exception",
        "hr_expense_pay_to_vendor",
        "hr_expense_payment",
        "hr_expense_payment_widget_amount",
        "hr_expense_sequence",
        "hr_expense_sequence_option",
        "hr_expense_tax_adjust",
        "hr_expense_tier_validation",
        "hr_expense_widget_o2m",
       
        "partner_bank_code",
        "sale_fixed_discount",
        "sale_force_invoiced",
        "sale_invoice_plan",
        "sale_invoice_plan_retention",
        "sale_management",
        "sale_order_line_analytic",
        "sale_order_line_stock_analytic",
        "sale_order_restrict_cancel_existing_invoice",
        "sale_stock_cancel_restriction",
        "sale_tax_adjust",
        # Agreement & Contract
        "agreement",
        "agreement_legal",
        # "agreement_legal_contract",
        "contract",
        "contract_invoice_plan",
        "contract_invoice_plan_selection",
        # Asset
        "account_asset_compute_batch",
        "account_asset_compute_batch_job",
        "account_asset_from_expense",
        "account_asset_low_value",
        "account_asset_management",
        "account_asset_transfer",
        # Inventory
        "l10n_th_gov_stock_request",
        "stock_analytic",
        "stock_card_report",
        "stock_no_negative",
        "stock_request",
        "stock_request_separate_picking",
        # Optional - st_george
        "st_george_hr_expense",
        "st_george_user_role",
        # Optional - Other App
    ],
}
